name: Build, publish and sign image

on:
  push:
    branches: [ main ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/msf:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@main

    - name: Cosign sign image with a key
      run: cosign sign --key env://COSIGN_PRIVATE_KEY ${TAGS}
      env:
        TAGS: ${{ secrets.DOCKER_HUB_USERNAME }}/msf@${{ steps.docker_build.outputs.digest }}
        COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
